=== DriftKing-DK/courses/Cours/M1/Cours/XML et Webservices/TPs/TP02/exo03/maths.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define the element for numeric values -->
    <xs:element name="cn" type="xs:integer" />

    <!-- Define the possible operation elements using xs:choice -->
    <xs:element name="plus" />
    <xs:element name="times" />
    <xs:element name="divide" />
    <xs:element name="minus" />
    <xs:element name="quotient" />

    <!-- Define the apply element that can contain child elements -->
    <xs:element name="apply">
        <xs:complexType>
            <xs:sequence>
                <!-- Use xs:choice to specify the operation elements -->
                <xs:choice minOccurs="1" maxOccurs="1">
                    <xs:element ref="plus" />
                    <xs:element ref="times" />
                    <xs:element ref="divide" />
                    <xs:element ref="minus" />
                    <xs:element ref="quotient" />
                </xs:choice>
                <!-- Second child is a sequence of cn elements -->

                <xs:element ref="cn" minOccurs="2" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Define the maths element that wraps everything -->
    <xs:element name="maths">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="apply" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="cn" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="cn" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="plus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="times" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="divide" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="minus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="quotient" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== DriftKing-DK/courses/Cours/M1S7/XML et Webservices/TPs/TP02/exo03/maths.xml
<?xml version="1.0" encoding="UTF-8"?>
<maths xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="maths.xsd">
    <!-- (2 * 3) -->
    <apply>
        <times />
        <cn>2</cn>
        <cn>3</cn>
    </apply>
    <!-- 2 * (2 + 3) -->
    <apply>
        <divide />
        <cn>2</cn>
        <apply>
            <plus />
            <cn>2</cn>
            <cn>3</cn>
        </apply>
    </apply>
    <!-- (2 * 3) + (4 * 5) -->
    <apply>
        <plus />
        <apply>
            <times />
            <cn>2</cn>
            <cn>3</cn>
        </apply>
        <apply>
            <times />
            <cn>4</cn>
            <cn>5</cn>
        </apply>
    </apply>
</maths>
